version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: davidses/corren-app
    depends_on:
      - db
    networks:
      - frontend
      - backend
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=corren-postgress-app
      - POSTGRES_PORT=5432
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: corren-nodejs-app
  db: 
    image: postgres:14.1-alpine
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    container_name: corren-postgress-app
networks:
  frontend:
  backend: